name: warehouse_env
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - backcall=0.2.0=pyh9f0ad1d_0
  - ca-certificates=2025.1.31=h8857fd0_0
  - comm=0.2.2=pyhd8ed1ab_1
  - debugpy=1.8.11=py39h6d0c2b6_0
  - decorator=5.1.1=pyhd8ed1ab_1
  - executing=2.1.0=pyhd8ed1ab_1
  - importlib-metadata=8.6.1=pyha770c72_0
  - ipykernel=6.29.5=pyh57ce528_0
  - ipython=8.12.0=pyhd1c38e8_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=pyh31011fe_1
  - libcxx=14.0.6=h9765a3e_0
  - libffi=3.4.4=hecd8cb5_1
  - libsodium=1.0.18=hbcb3906_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - ncurses=6.4=hcec6c5f_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.4.1=hc426f3f_0
  - packaging=24.2=pyhd8ed1ab_2
  - parso=0.8.4=pyhd8ed1ab_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.0=py39hecd8cb5_0
  - platformdirs=4.3.6=pyhd8ed1ab_1
  - prompt-toolkit=3.0.50=pyha770c72_0
  - prompt_toolkit=3.0.50=hd8ed1ab_0
  - psutil=6.1.1=py39h80efdc8_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.1=pyhd8ed1ab_0
  - python=3.9.21=hce00570_1
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python_abi=3.9=2_cp39
  - pyzmq=24.0.1=py39hed8f129_1
  - readline=8.2=hca72f7f_0
  - setuptools=75.8.0=py39hecd8cb5_0
  - six=1.17.0=pyhd8ed1ab_0
  - sqlite=3.45.3=h6c40b1e_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.14=h4d00af3_0
  - tornado=6.4.2=py39h80efdc8_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.12.2=pyha770c72_1
  - tzdata=2025a=h04d1e81_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=py39hecd8cb5_0
  - xz=5.6.4=h46256e1_1
  - zeromq=4.3.5=hcec6c5f_0
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib=1.2.13=h4b97444_1
  - pip:
    - certifi==2025.1.31
    - charset-normalizer==3.4.1
    - contourpy==1.3.0
    - cycler==0.12.1
    - fonttools==4.56.0
    - idna==3.10
    - importlib-resources==6.5.2
    - kiwisolver==1.4.7
    - matplotlib==3.9.4
    - numpy==2.0.2
    - pillow==11.1.0
    - pooch==1.8.2
    - pyparsing==3.2.1
    - pyvista==0.44.2
    - requests==2.32.3
    - scooby==0.10.0
    - urllib3==2.3.0
    - vtk==9.3.1
prefix: /opt/anaconda3/envs/warehouse_env
